<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer
{
    const METHOD_MAPPING = array(
  'App\\Controller\\Home' => 'get5bb8ed5ed570b227322201',
);

    protected function get5bb8ed5ed570b227322201()
    {
        $object = new App\Controller\Home();
        return $object;
    }
}
